[package]
name = "nu_plugin_highlight"
version = "1.1.4+0.94.0"
authors = ["Tim 'Piepmatz' Hesse"]
edition = "2021"
repository = "https://github.com/cptpiepmatz/nu-plugin-highlight"
description = "A nushell plugin for syntax highlighting"
license = "MIT"
keywords = ["nu", "plugin", "syntax", "highlighting"]
categories = ["command-line-utilities", "development-tools", "value-formatting"]

[dependencies]
# nu
nu-plugin = { version = "0.94", path = "../nushell/crates/nu-plugin" }
nu-protocol = { version = "0.94", path = "../nushell/crates/nu-protocol" }
nu-path = { version = "0.94", path = "../nushell/crates/nu-path" }

# highlighting
syntect = "5"
nu-ansi-term = "0.50"
ansi_colours = "1"
bat = { version = "0.24", default-features = false }
