[package]
name = "nu_plugin_highlight"
version = "1.3.0-0.97.2"
authors = ["Tim 'Piepmatz' Hesse"]
edition = "2021"
repository = "https://github.com/cptpiepmatz/nu-plugin-highlight"
description = "A nushell plugin for syntax highlighting"
license = "MIT"
keywords = ["nu", "plugin", "syntax", "highlighting"]
categories = ["command-line-utilities", "development-tools", "value-formatting"]
publish = false

[dependencies]
# nu
nu-plugin = { version = "0.97.2", git = "https://github.com/nushell/nushell.git" }
nu-protocol = { version = "0.97.2", git = "https://github.com/nushell/nushell.git" }
nu-path = { version = "0.97.2", git = "https://github.com/nushell/nushell.git" }

# highlighting
syntect = "5"
nu-ansi-term = "0.50"
ansi_colours = "1"
bat = { version = "0.24", default-features = false }

# guess the type
mime_guess = "2"
